#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Oskar Wickström"
email: oskar.wickstrom@gmail.com
description: "Software design, testing, functional programming, and other delightful things."
baseurl: ""
url: "https://wickstrom.tech"
twitter_username: owickstrom
github_username:  owickstrom

navigation:
  - text: Writing
    url: /writing.html
  - text: Talks
    url: /talks.html
  - text: Projects
    url: /projects.html
  - text: Work
    url: /work.html
  - text: About
    url: /about.html

# Build settings
markdown: Pandoc

sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-pandoc

pandoc:
  extensions:
    - mathjax
    - highlight-style: pygments
    - filter: unicode-numbers
    - filter: pandoc-include-code
    - syntax-definition: _tools/hedgehog.xml

plantuml:
  plantuml_jar: ../deps/plantuml.jar     # path to plantuml jar
  tmp_folder: generated

local: true
